<?php

/**
 * @file
 * Primary module hooks for DrupalX Payment.
 */

/**
 * Implements hook_theme().
 */
function dx_payment_theme(array $existing, $type, $theme, $path): array {
  return [
    'dx_payment_checkout' => [
      'variables' => [
        'product' => [],
        'endpoint' => '/dx/payment/create',
        'payment_groups' => [],
        'default_channel' => 'card',
      ],
    ],
  ];
}
