<?php

declare(strict_types=1);

/**
 * @file
 * Install hooks for dx_migrate.
 */

/**
 * Implements hook_install().
 */
function dx_migrate_install(): void {
  if (\Drupal::entityTypeManager()->getStorage('user_role')->load('administrator')) {
    user_role_grant_permissions('administrator', ['administer dx migrate']);
  }
}

/**
 * Grant review permission for existing installs.
 */
function dx_migrate_update_10001(): void {
  if (\Drupal::entityTypeManager()->getStorage('user_role')->load('administrator')) {
    user_role_grant_permissions('administrator', ['administer dx migrate']);
  }
}
